[package]
name = "harmonic_coordinates"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
eframe = { version = "0.26.2", features = ["wgpu", "persistence"] }
egui = "0.26.2"
env_logger = "0.11.3"
glam = "0.25.0"
log = "0.4.21"
serde = "1.0.197"
tobj = "4.0.1"
