[package]
name = "harmonic_coordinates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.26.2", features = ["wgpu"] }
glam = "0.25.0"
tobj = "4.0.1"
